# Generated by Django 4.2 on 2023-04-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
