# Generated by Django 4.2 on 2023-04-22 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_brand_user_image_user_price_user_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='season',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
